import { BubblePosition } from "../types/Bubble";
import { BlockConfig } from "../types/Config";
import { PossiblePages } from "../types/Pages";

export const ourteam_config: BlockConfig = {
  possiblePages: [PossiblePages.HOME, PossiblePages.FAQ],
  contents: {
    rightSection: {
      sectionInfo: {
        sectionTitle: "All",
      },
      ourteamMainContainer: {
        background_color: "white",
      },
      ourteamUpTitle: {
        id: "ourteam_up_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "The team",
        color: "purple",
      },
      ourteamMainTitle: {
        id: "ourteam_main_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Meet the team behind Untitled",
        color: "#000000",
      },
      ourteamDesc: {
        id: "ourteam_desc_id",
        bubble: true,
        bubblePosition: BubblePosition.BOTTOM,
        render: true,
        text: "We're a small team that loves to create great experiences and make meaningful connections between builders and customers. Join our remote team!",
        color: "gray",
      },

      ourteamPerson_0_Image: {
        id: "ourteam_person_0_image_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        img_src: "/blocks/images/ourteam01.png",
      },
      ourteamPerson_0_Fullname: {
        id: "ourteam_person_0_fullname_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Olivia Rhye",
        color: "#000000",
      },
      ourteamPerson_0_JobTitle: {
        id: "ourteam_person_0_job_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Founder & CEO",
        color: "purple",
      },
      ourteamPerson_0_Desc: {
        id: "ourteam_person_0_desc_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Former co-founder of Opendoor. Early staff at Spotify and Clearbit.",
        color: "gray",
      },
      ourteamPerson_0_Icon_0: {
        id: "ourteam_person_0_icon_0_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-twitter",
        color: "#6c757d",
      },
      ourteamPerson_0_Icon_1: {
        id: "ourteam_person_0_icon_1_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-linkedin",
        color: "#6c757d",
      },
      ourteamPerson_0_Icon_2: {
        id: "ourteam_person_0_icon_2_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-github",
        color: "#6c757d",
      },

      ourteamPerson_1_Image: {
        id: "ourteam_person_1_image_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        img_src: "/blocks/images/ourteam02.png",
      },
      ourteamPerson_1_Fullname: {
        id: "ourteam_person_1_fullname_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Phoenix Baker",
        color: "#000000",
      },
      ourteamPerson_1_JobTitle: {
        id: "ourteam_person_1_job_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Engineering Manager",
        color: "purple",
      },
      ourteamPerson_1_Desc: {
        id: "ourteam_person_1_desc_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Lead engineering teams at Figma, Pitch, and Protocol Labs.",
        color: "gray",
      },
      ourteamPerson_1_Icon_0: {
        id: "ourteam_person_1_icon_1_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-twitter",
        color: "#6c757d",
      },
      ourteamPerson_1_Icon_1: {
        id: "ourteam_person_1_icon_1_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-linkedin",
        color: "#6c757d",
      },
      ourteamPerson_1_Icon_2: {
        id: "ourteam_person_1_icon_2_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-github",
        color: "#6c757d",
      },

      ourteamPerson_2_Image: {
        id: "ourteam_person_2_image_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        img_src: "/blocks/images/ourteam03.png",
      },
      ourteamPerson_2_Fullname: {
        id: "ourteam_person_2_fullname_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Lana Steiner",
        color: "#000000",
      },
      ourteamPerson_2_JobTitle: {
        id: "ourteam_person_2_job_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Product Manager",
        color: "purple",
      },
      ourteamPerson_2_Desc: {
        id: "ourteam_person_2_desc_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Former PM for Linear, Lambda School, and On Deck.",
        color: "gray",
      },
      ourteamPerson_2_Icon_0: {
        id: "ourteam_person_2_icon_2_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-twitter",
        color: "#6c757d",
      },
      ourteamPerson_2_Icon_1: {
        id: "ourteam_person_2_icon_2_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-linkedin",
        color: "#6c757d",
      },
      ourteamPerson_2_Icon_2: {
        id: "ourteam_person_2_icon_2_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-github",
        color: "#6c757d",
      },

      ourteamPerson_3_Image: {
        id: "ourteam_person_3_image_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        img_src: "/blocks/images/ourteam04.png",
      },
      ourteamPerson_3_Fullname: {
        id: "ourteam_person_3_fullname_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Demi Wilkinson",
        color: "#000000",
      },
      ourteamPerson_3_JobTitle: {
        id: "ourteam_person_3_job_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Frontend Developer",
        color: "purple",
      },
      ourteamPerson_3_Desc: {
        id: "ourteam_person_3_desc_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Former frontend dev for Linear, Coinbase, and Postscript.",
        color: "gray",
      },
      ourteamPerson_3_Icon_0: {
        id: "ourteam_person_3_icon_3_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-twitter",
        color: "#6c757d",
      },
      ourteamPerson_3_Icon_1: {
        id: "ourteam_person_3_icon_3_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-linkedin",
        color: "#6c757d",
      },
      ourteamPerson_3_Icon_2: {
        id: "ourteam_person_3_icon_2_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-github",
        color: "#6c757d",
      },

      ourteamPerson_4_Image: {
        id: "ourteam_person_4_image_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        img_src: "/blocks/images/ourteam05.png",
      },
      ourteamPerson_4_Fullname: {
        id: "ourteam_person_4_fullname_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Candice Wu",
        color: "#000000",
      },
      ourteamPerson_4_JobTitle: {
        id: "ourteam_person_4_job_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Backend Developer",
        color: "purple",
      },
      ourteamPerson_4_Desc: {
        id: "ourteam_person_4_desc_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Lead backend dev at Clearbit. Former Clearbit and Loom.",
        color: "gray",
      },
      ourteamPerson_4_Icon_0: {
        id: "ourteam_person_4_icon_4_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-twitter",
        color: "#6c757d",
      },
      ourteamPerson_4_Icon_1: {
        id: "ourteam_person_4_icon_4_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-linkedin",
        color: "#6c757d",
      },
      ourteamPerson_4_Icon_2: {
        id: "ourteam_person_4_icon_2_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-github",
        color: "#6c757d",
      },

      ourteamPerson_5_Image: {
        id: "ourteam_person_5_image_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        img_src: "/blocks/images/ourteam06.png",
      },
      ourteamPerson_5_Fullname: {
        id: "ourteam_person_5_fullname_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Natali Craig",
        color: "#000000",
      },
      ourteamPerson_5_JobTitle: {
        id: "ourteam_person_5_job_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Product Designer",
        color: "purple",
      },
      ourteamPerson_5_Desc: {
        id: "ourteam_person_5_desc_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Former frontend dev for Linear, Coinbase, and Postscript.",
        color: "gray",
      },
      ourteamPerson_5_Icon_0: {
        id: "ourteam_person_5_icon_5_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-twitter",
        color: "#6c757d",
      },
      ourteamPerson_5_Icon_1: {
        id: "ourteam_person_5_icon_5_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-linkedin",
        color: "#6c757d",
      },
      ourteamPerson_5_Icon_2: {
        id: "ourteam_person_5_icon_2_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-dribbble",
        color: "#6c757d",
      },

      ourteamPerson_6_Image: {
        id: "ourteam_person_6_image_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        img_src: "/blocks/images/ourteam07.png",
      },
      ourteamPerson_6_Fullname: {
        id: "ourteam_person_6_fullname_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Drew Cano",
        color: "#000000",
      },
      ourteamPerson_6_JobTitle: {
        id: "ourteam_person_6_job_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "UX Researcher",
        color: "purple",
      },
      ourteamPerson_6_Desc: {
        id: "ourteam_person_6_desc_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Lead user research for Slack. Contractor for Netflix and Udacity.",
        color: "gray",
      },
      ourteamPerson_6_Icon_0: {
        id: "ourteam_person_6_icon_6_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-twitter",
        color: "#6c757d",
      },
      ourteamPerson_6_Icon_1: {
        id: "ourteam_person_6_icon_6_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-linkedin",
        color: "#6c757d",
      },
      ourteamPerson_6_Icon_2: {
        id: "ourteam_person_6_icon_2_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-behance",
        color: "#6c757d",
      },

      ourteamPerson_7_Image: {
        id: "ourteam_person_7_image_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        img_src: "/blocks/images/ourteam08.png",
      },
      ourteamPerson_7_Fullname: {
        id: "ourteam_person_7_fullname_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Orlando Diggs",
        color: "#000000",
      },
      ourteamPerson_7_JobTitle: {
        id: "ourteam_person_7_job_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Customer Success",
        color: "purple",
      },
      ourteamPerson_7_Desc: {
        id: "ourteam_person_7_desc_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Lead CX at Wealthsimple. Former PagerDuty and Squeen.",
        color: "gray",
      },
      ourteamPerson_7_Icon_0: {
        id: "ourteam_person_7_icon_7_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-twitter",
        color: "#6c757d",
      },
      ourteamPerson_7_Icon_1: {
        id: "ourteam_person_7_icon_7_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-linkedin",
        color: "#6c757d",
      },
      ourteamPerson_7_Icon_2: {
        id: "ourteam_person_7_icon_2_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-facebook",
        color: "#6c757d",
      },
    },
  },
};
