import { BubblePosition } from "../types/Bubble";
import { BlockConfig } from "../types/Config";
import { PossiblePages } from "../types/Pages";

export const footer_config: BlockConfig = {
  possiblePages: [PossiblePages.HOME, PossiblePages.FAQ],
  contents: {
    rightSection: {
      sectionInfo: {
        sectionTitle: "all",
      },
      footerMainContainer: {
        id: "footer_main_container",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
      },
      footerTopSection: {
        background_color: "#f8f9fa",
      },
      footerMiddleSection: {
        id: "footer_middle_section_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        background_color: "#ffffff",
      },
      footerBottomSection: {
        id: "footer_bottom_section_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        background_color: "#f9f9f9",
      },
      footerTSIcon_0: {
        id: "footer_ts_0_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        color: "white",
        background_color: "#fd580d",
        class: "fas fa-check",
      },
      footerTSTitle_0: {
        id: "footer_ts_0_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Easy to use",
        color: "#000000",
      },
      footerTSDesc_0: {
        id: "footer_ts_0_desc_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Things on a very small that you have any direct",
        color: "#6c757d",
      },

      footerTSIcon_1: {
        id: "footer_ts_1_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        color: "white",
        background_color: "#fd580d",
        class: "fas fa-rocket",
      },
      footerTSTitle_1: {
        id: "footer_ts_1_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Easy to use",
        color: "#000000",
      },
      footerTSDesc_1: {
        id: "footer_ts_1_desc_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Things on a very small that you have any direct",
        color: "#6c757d",
      },

      footerTSIcon_2: {
        id: "footer_ts_2_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        color: "white",
        background_color: "#fd580d",
        class: "fas fa-cog",
      },
      footerTSTitle_2: {
        id: "footer_ts_2_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Easy to use",
        color: "#000000",
      },
      footerTSDesc_2: {
        id: "footer_ts_2_desc_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Things on a very small that you have any direct",
        color: "#6c757d",
      },

      footerTSIcon_3: {
        id: "footer_ts_3_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        color: "white",
        background_color: "#fd580d",
        class: "fas fa-shield-alt",
      },
      footerTSTitle_3: {
        id: "footer_ts_3_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Easy to use",
        color: "#000000",
      },
      footerTSDesc_3: {
        id: "footer_ts_3_desc_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Things on a very small that you have any direct",
        color: "#6c757d",
      },

      footerMSHead_00: {
        id: "footer_ms_head_00_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Company Info",
        color: "#000000",
      },
      footerMSSubHead_01: {
        id: "footer_ms_sub_head_01_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "About us",
        color: "grey",
      },
      footerMSSubHead_02: {
        id: "footer_ms_sub_head_02_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Carrier",
        color: "grey",
      },
      footerMSSubHead_03: {
        id: "footer_ms_sub_head_03_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "We are hiring",
        color: "grey",
      },
      footerMSSubHead_04: {
        id: "footer_ms_sub_head_04_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Blog",
        color: "grey",
      },

      footerMSHead_10: {
        id: "footer_ms_Head_10_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Legal",
        color: "#000000",
      },
      footerMSSubHead_11: {
        id: "footer_ms_sub_Head_11_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "About us",
        color: "grey",
      },
      footerMSSubHead_12: {
        id: "footer_ms_sub_Head_12_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Carrier",
        color: "grey",
      },
      footerMSSubHead_13: {
        id: "footer_ms_sub_Head_13_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "We are hiring",
        color: "grey",
      },
      footerMSSubHead_14: {
        id: "footer_ms_sub_Head_14_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Blog",
        color: "grey",
      },

      footerMSHead_20: {
        id: "footer_ms_Head_20_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Featurs",
        color: "#000000",
      },
      footerMSSubHead_21: {
        id: "footer_ms_sub_Head_21_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Business Marketing",
        color: "grey",
      },
      footerMSSubHead_22: {
        id: "footer_ms_sub_Head_22_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "User Analytic",
        color: "grey",
      },
      footerMSSubHead_23: {
        id: "footer_ms_sub_Head_23_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Live Chat",
        color: "grey",
      },
      footerMSSubHead_24: {
        id: "footer_ms_sub_Head_24_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Unlimited Support",
        color: "grey",
      },

      footerMSHead_30: {
        id: "footer_ms_Head_30_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Resources",
        color: "#000000",
      },
      footerMSSubHead_31: {
        id: "footer_ms_sub_Head_31_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "IOS & Android",
        color: "grey",
      },
      footerMSSubHead_32: {
        id: "footer_ms_sub_Head_32_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Watch a Demo",
        color: "grey",
      },
      footerMSSubHead_33: {
        id: "footer_ms_sub_Head_33_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Customers",
        color: "grey",
      },
      footerMSSubHead_34: {
        id: "footer_ms_sub_Head_34_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "API",
        color: "grey",
      },

      footerMSHead_40: {
        id: "footer_ms_Head_40_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Get In Touch",
        color: "#000000",
      },
      footerMSSubHead_41: {
        id: "footer_ms_sub_Head_41_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "(480) 555-0103",
        color: "grey",
        class: "fas fa-phone",
        icon_color: "#2196f3",
      },
      footerMSSubHead_42: {
        id: "footer_ms_sub_Head_42_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "4577 Wahington Ave.",
        color: "grey",
        class: "fas fa-map-marker-alt",
        icon_color: "#2196f3",
      },
      footerMSSubHead_43: {
        id: "footer_ms_sub_Head_43_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "debra.holt@example.com",
        color: "grey",
        class: "fas fa-envelope",
        icon_color: "#2196f3",
      },

      footerBSTitle: {
        id: "footer_bs_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Consulting Agency For Your Business",
        color: "#000000",
      },
      footerBSDesc: {
        id: "footer_bs_Desc_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "the quick fox jumps over the lazy dog",
        color: "grey !important",
      },
      footerBSContactUsButton: {
        id: "footer_bs_contact_us_button_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        text: "Contact us",
        render: true,
        background_color: "rgb(13, 110, 253)",
        color: "white",
        border_radius: "0.375rem",
      },
    },
  },
};
