import { BubblePosition } from "../types/Bubble";
import { BlockConfig } from "../types/Config";
import { PossiblePages } from "../types/Pages";

export const pricingplan_config: BlockConfig = {
  possiblePages: [PossiblePages.HOME, PossiblePages.FAQ],
  contents: {
    rightSection: {
      sectionInfo: {
        sectionTitle: "All",
      },
      pricingplanMainContainer: {
        background_image: "blocks/images/Pricing_plan_descktop_background.png",
      },
      pricingplanUpTitle: {
        id: "pricingplan_up_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Pricing plans",
        color: "#7f56d9",
        background_color: "#d9d7e6",
      },
      pricingplanMainTitle: {
        id: "pricingplan_main_title_id",
        bubble: true,
        bubblePosition: BubblePosition.BOTTOM,
        render: true,
        text: "Plans for all sizes",
        color: "#341578",
      },
      pricingplanDesc: {
        id: "pricingplan_desc_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Simple, transparent pricing that grows with you. Try any plan free for 30 days.",
        color: "#7f56d9",
      },

      pricingplanBillingToggleSwitch: {
        id: "pricingplan_billing_toggle_switch_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        background_color: "#7f56d9",
      },
      pricingplanBillingToggleTitle: {
        id: "pricingplan_billing_toggle_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Annual pricing",
        color: "#7f56d9",
      },
      pricingplanBillingTogglePercent: {
        id: "pricingplan_billing_toggle_percent_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "(save 20%)",
        color: "#7f56d9",
      },

      pricingplanCard_0: {
        id: "pricingplan_card_0_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        background_color: "white",
        box_shadow_color: "rgba(106, 13, 173, 0.2)",
      },
      pricingplanCard_0_Icon: {
        id: "pricingplan_card_0_icon_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        background_color: "#d9d7e6",
        color: "#7f56d9",
        class: "bi bi-box-seam",
      },
      pricingplanCard_0_Title: {
        id: "pricingplan_card_0_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Basic plan",
        color: "#7f56d9",
      },
      pricingplanCard_0_MTH: {
        id: "pricingplan_card_0_mth_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "$10/mth",
        color: "#333",
      },
      pricingplanCard_0_Billed: {
        id: "pricingplan_card_0_billed_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Billed annually",
        color: "gray",
      },
      pricingplanCard_0_CardHeader: {
        border_bottom_color: "rgba(106, 13, 173, 0.1)",
      },

      pricingplanCard_0_ItemIcon_0: {
        id: "pricingplan_card_0_item_icon_0_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-check",
        color: "#7f56d9",
        background_color: "#d9d7e6",
      },
      pricingplanCard_0_ItemTitle_0: {
        id: "pricingplan_card_0_item_title_0_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Access to all basic features",
        color: "gray",
      },
      pricingplanCard_0_ItemIcon_1: {
        id: "pricingplan_card_0_item_icon_1_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-check",
        color: "#7f56d9",
        background_color: "#d9d7e6",
      },
      pricingplanCard_0_ItemTitle_1: {
        id: "pricingplan_card_0_item_title_1_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Basic reporting and analytics",
        color: "gray",
      },
      pricingplanCard_0_ItemIcon_2: {
        id: "pricingplan_card_0_item_icon_2_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-check",
        color: "#7f56d9",
        background_color: "#d9d7e6",
      },
      pricingplanCard_0_ItemTitle_2: {
        id: "pricingplan_card_0_item_title_2_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Up to 10 individual users",
        color: "gray",
      },
      pricingplanCard_0_ItemIcon_3: {
        id: "pricingplan_card_0_item_icon_3_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-check",
        color: "#7f56d9",
        background_color: "#d9d7e6",
      },
      pricingplanCard_0_ItemTitle_3: {
        id: "pricingplan_card_0_item_title_3_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "200B individual data each user",
        color: "gray",
      },
      pricingplanCard_0_ItemIcon_4: {
        id: "pricingplan_card_0_item_icon_4_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-check",
        color: "#7f56d9",
        background_color: "#d9d7e6",
      },
      pricingplanCard_0_ItemTitle_4: {
        id: "pricingplan_card_0_item_title_4_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Basic chat and email support",
        color: "gray",
      },
      pricingplanCard_0_Button: {
        id: "pricingplan_card_0_button_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Get started",
        color: "white",
        border_color: "#7f56d9",
        background_color: "#7f56d9",
        border_radius: "0.375rem",
      },

      pricingplanCard_1: {
        id: "pricingplan_card_1_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        background_color: "white",
        box_shadow_color: "rgba(106, 13, 173, 0.2)",
      },
      pricingplanCard_1_Icon: {
        id: "pricingplan_card_1_icon_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        background_color: "#d9d7e6",
        color: "#7f56d9",
        class: "bi bi-briefcase",
      },
      pricingplanCard_1_Title: {
        id: "pricingplan_card_1_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Business plan",
        color: "#7f56d9",
      },
      pricingplanCard_1_MTH: {
        id: "pricingplan_card_1_mth_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "$20/mth",
        color: "#333",
      },
      pricingplanCard_1_Billed: {
        id: "pricingplan_card_1_billed_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Billed annually",
        color: "gray",
      },
      pricingplanCard_1_CardHeader: {
        border_bottom_color: "rgba(106, 13, 173, 0.1)",
      },

      pricingplanCard_1_ItemIcon_0: {
        id: "pricingplan_card_1_item_icon_0_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-check",
        color: "#7f56d9",
        background_color: "#d9d7e6",
      },
      pricingplanCard_1_ItemTitle_0: {
        id: "pricingplan_card_1_item_title_0_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "200+ integrations",
        color: "gray",
      },
      pricingplanCard_1_ItemIcon_1: {
        id: "pricingplan_card_1_item_icon_1_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-check",
        color: "#7f56d9",
        background_color: "#d9d7e6",
      },
      pricingplanCard_1_ItemTitle_1: {
        id: "pricingplan_card_1_item_title_1_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Advanced reporting and analytics",
        color: "gray",
      },
      pricingplanCard_1_ItemIcon_2: {
        id: "pricingplan_card_1_item_icon_2_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-check",
        color: "#7f56d9",
        background_color: "#d9d7e6",
      },
      pricingplanCard_1_ItemTitle_2: {
        id: "pricingplan_card_1_item_title_2_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Up to 20 individual users",
        color: "gray",
      },
      pricingplanCard_1_ItemIcon_3: {
        id: "pricingplan_card_1_item_icon_3_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-check",
        color: "#7f56d9",
        background_color: "#d9d7e6",
      },
      pricingplanCard_1_ItemTitle_3: {
        id: "pricingplan_card_1_item_title_3_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "400B individual data each user",
        color: "gray",
      },
      pricingplanCard_1_ItemIcon_4: {
        id: "pricingplan_card_1_item_icon_4_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-check",
        color: "#7f56d9",
        background_color: "#d9d7e6",
      },
      pricingplanCard_1_ItemTitle_4: {
        id: "pricingplan_card_1_item_title_4_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Priority chat and email support",
        color: "gray",
      },
      pricingplanCard_1_Button: {
        id: "pricingplan_card_1_button_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Get started",
        color: "white",
        border_color: "#7f56d9",
        background_color: "#7f56d9",
        border_radius: "0.375rem",
      },

      pricingplanCard_2: {
        id: "pricingplan_card_2_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        background_color: "white",
        box_shadow_color: "rgba(106, 13, 173, 0.2)",
      },
      pricingplanCard_2_Icon: {
        id: "pricingplan_card_2_icon_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        background_color: "#d9d7e6",
        color: "#7f56d9",
        class: "bi bi-rocket",
      },
      pricingplanCard_2_Title: {
        id: "pricingplan_card_2_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Enterprise plan",
        color: "#7f56d9",
      },
      pricingplanCard_2_MTH: {
        id: "pricingplan_card_2_mth_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "$40/mth",
        color: "#333",
      },
      pricingplanCard_2_Billed: {
        id: "pricingplan_card_2_billed_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Billed annually",
        color: "gray",
      },
      pricingplanCard_2_CardHeader: {
        border_bottom_color: "rgba(106, 13, 173, 0.1)",
      },

      pricingplanCard_2_ItemIcon_0: {
        id: "pricingplan_card_2_item_icon_0_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-check",
        color: "#7f56d9",
        background_color: "#d9d7e6",
      },
      pricingplanCard_2_ItemTitle_0: {
        id: "pricingplan_card_2_item_title_0_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Advanced custom fields",
        color: "gray",
      },
      pricingplanCard_2_ItemIcon_1: {
        id: "pricingplan_card_2_item_icon_1_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-check",
        color: "#7f56d9",
        background_color: "#d9d7e6",
      },
      pricingplanCard_2_ItemTitle_1: {
        id: "pricingplan_card_2_item_title_1_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Audit log and data history",
        color: "gray",
      },
      pricingplanCard_2_ItemIcon_2: {
        id: "pricingplan_card_2_item_icon_2_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-check",
        color: "#7f56d9",
        background_color: "#d9d7e6",
      },
      pricingplanCard_2_ItemTitle_2: {
        id: "pricingplan_card_2_item_title_2_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Unlimited individual users",
        color: "gray",
      },
      pricingplanCard_2_ItemIcon_3: {
        id: "pricingplan_card_2_item_icon_3_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-check",
        color: "#7f56d9",
        background_color: "#d9d7e6",
      },
      pricingplanCard_2_ItemTitle_3: {
        id: "pricingplan_card_2_item_title_3_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Unlimited individual data",
        color: "gray",
      },
      pricingplanCard_2_ItemIcon_4: {
        id: "pricingplan_card_2_item_icon_4_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-check",
        color: "#7f56d9",
        background_color: "#d9d7e6",
      },
      pricingplanCard_2_ItemTitle_4: {
        id: "pricingplan_card_2_item_title_4_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Personalised+priority service",
        color: "gray",
      },
      pricingplanCard_2_Button: {
        id: "pricingplan_card_2_button_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Get started",
        color: "white",
        border_color: "#7f56d9",
        background_color: "#7f56d9",
        border_radius: "0.375rem",
      },
    },
  },
};
