import { BubblePosition } from "../types/Bubble";
import { BlockConfig } from "../types/Config";
import { ResponsiveVisibility } from "../types/Html";
import { PossiblePages } from "../types/Pages";

export const hero_config: BlockConfig = {
  possiblePages: [PossiblePages.HOME, PossiblePages.FAQ],
  contents: {
    countersSection: {
      sectionInfo: {
        sectionTitle: "Counters Section",
      },
      heroRentersNumber: {
        id: "hero_renters_number_id",
        name: "Counter",
        bubble: true,
        bubblePosition: BubblePosition.LEFT,
        render: true,
        text: `50K+`,
        color: "#0d6efd",
      },
      heroRentersTitle: {
        id: "hero_renters_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: `renters`,
        color: "#6c757d",
      },
      heroRentersNumTitleBorder: {
        id: "hero_renters_num_title_border_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        border_color: "rgb(200 214 200)",
      },
      heroPropertiesNumber: {
        id: "hero_properties_number_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: `50K+`,
        color: "#0d6efd",
      },
      heroPropertiesTitle: {
        id: "hero_properties_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: `properties`,
        color: "#6c757d",
      },
      heroPropertiesNumTitleBorder: {
        id: "hero_properties_num_title_border_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        border_color: "rgb(200 214 200)",
      },

      heroMobileModeRentersNumber: {
        id: "hero_mobile_mode_renters_number_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: `50K+`,
        color: "#0d6efd",
      },
      heroMobileModeRentersTitle: {
        id: "hero_mobile_mode_renters_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: `renters`,
        color: "#6c757d",
      },
      heroMobileModeRentersNumTitleBorder: {
        id: "hero_mobile_mode_renters_num_title_border_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        border_color: "rgb(200 214 200)",
      },
      heroMobileModePropertiesNumber: {
        id: "hero_mobile_mode_properties_number_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: `50K+`,
        color: "#0d6efd",
      },
      heroMobileModePropertiesTitle: {
        id: "hero_mobile_mode_properties_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: `properties`,
        color: "#6c757d",
      },
      heroMobileModePropertiesNumTitleBorder: {
        id: "hero_mobile_mode_properties_num_title_border_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        border_color: "rgb(200 214 200)",
      },
    },
    rightSection: {
      sectionInfo: {
        sectionTitle: "Right Section",
      },
      heroMainContainer: {
        id: "hero_main_container_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        background_color: "#ffffff",
        background: "url('/blocks/images/estatery-background.png')",
      },

      // heroMainImage: {
      //   id: "hero_main_image_id",
      //   bubble: true,
      //   bubblePosition: BubblePosition.TOP,
      //   render: true,
      //   img_src: "/blocks/images/hero_Image.png",
      // },
      heroTitle: {
        id: "hero_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        isRichText: true,
        text: `Buy, rent, or sell<br>
                your property<br>
                easily`,
        color: "black",
      },
      heroDesc: {
        id: "hero_desc_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: `A great platform to buy, sell, or even rent your<br>
                properties without any commisions.`,
        color: "#42494f",
      },

      heroMobileModeSearchInput: {
        id: "hero_mobile_search_input_id",
        responsiveVisibility: ResponsiveVisibility.Mobile,
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: `properties`,
        color: "#6c757d",
        placeholder_text: "Search location",
        placeholder_color: "grey",
      },

      heroMobileModeSearchButton: {
        id: "hero_mobile_login_button_id",
        responsiveVisibility: ResponsiveVisibility.Mobile,
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        icon_color: "#ffffff",
        background_color: "#3361FF",
        border_color: "#3361FF",
        border_radius: "0.375rem",
        class: "fa fa-search",
      },
      heroRentBuySellBorderBottomColor: {
        border_bottom_color: "#1A3E5E",
      },
      heroRentTitle: {
        id: "hero_rent_title_id",
        name: "Counter Tab 1",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: `Rent`,
        color: "#0d6efd",
        border_bottom_color: "#3361FF",
      },
      heroBuyTitle: {
        id: "hero_buy_title_id",
        name: "Counter Tab 2",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: `Buy`,
        color: "#495057",
      },
      heroSellTitle: {
        id: "hero_sell_title_id",
        name: "Counter Tab 3",
        bubble: true,
        bubblePosition: BubblePosition.RIGHT,
        render: true,
        text: `Sell`,
        color: "#495057",
      },

      heroSearchCard: {
        background_color: "#ffffff",
        box_shadow_color: "#0000001a",
      },
      heroLocationTitle: {
        id: "hero_location_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: `Location`,
        color: "#495057",
      },
      heroLocationValue: {
        id: "hero_location_value_id",
        bubble: true,
        bubblePosition: BubblePosition.LEFT,
        render: true,
        text: `Barcelona, Spain`,
        color: "#dee2e6",
      },
      heroWhenTitle: {
        id: "hero_when_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: `When`,
        color: "#495057",
      },
      heroWhenValue: {
        id: "hero_when_value_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: `Select Move-in Date`,
        color: "#dee2e6",
        class: "fa fa-calendar",
        icon_color: "#dee2e6",
      },
      heroBrowsePropertiesButton: {
        id: "footer_browse_properties_button_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        text: "Browse Properties",
        render: true,
        background_color: "rgb(13, 110, 253)",
        color: "#ffffff",
        border_radius: "0.375rem",
      },
    },
  },
};
