import { BubblePosition } from "../types/Bubble";
import { BlockConfig } from "../types/Config";
import { PossiblePages } from "../types/Pages";

export const signup_config: BlockConfig = {
  possiblePages: [PossiblePages.HOME, PossiblePages.FAQ],
  contents: {
    rightSection: {
      sectionInfo: {
        sectionTitle: "All",
      },
      formMainContainer: {
        background_color: "white",
      },
      formTitle: {
        id: "signup_form_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        text: "ثبت نام",
        render: true,
        color: " #000000",
      },
      formTitleDescription: {
        id: "signup_form_title_description_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        text: "Start your 30-day free trial",
        render: true,
        color: " var(--bs-secondary-color)!important",
      },
      formNameLabel: {
        id: "signup_form_name_label_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        text: "Name*",
        render: true,
        color: "#212529",
      },
      formNameField: {
        id: "signup_form_name_field_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        placeholder_text: "Enter your name",
        placeholder_color: "#212529",
        border_color: "var(--bs-border-color)",
      },
      formEmailLabel: {
        id: "signup_form_email_label_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        text: "Email*",
        render: true,
        color: "#212529",
      },
      formEmailField: {
        id: "signup_form_email_field_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        placeholder_text: "Enter your email",
        placeholder_color: "#212529",
        border_color: "var(--bs-border-color)",
      },
      formPasswordLabel: {
        id: "signup_form_password_label_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        text: "Password*",
        render: true,
        color: "#212529",
      },
      formPasswordField: {
        id: "signup_form_password_field_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        placeholder_text: "Enter your password",
        placeholder_color: "#212529",
        border_color: "var(--bs-border-color)",
      },
      formPasswordLimitation: {
        id: "signup_form_password_limitation_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Must be at least 8 characters.",
        color: " var(--bs-secondary-color)!important",
      },
      formCreateAccountButton: {
        id: "signup_form_create_account_button_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        text: "Create account",
        render: true,
        background_color: "#7c3aed",
        color: "white",
        border_radius: "0.375rem",
      },
      formSignupWithGoogleButton: {
        id: "signup_form_signup_with_google_button_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        text: "&copy; Sign up with Google",
        render: true,
        color: " var(--bs-secondary-color)!important",
        border_color: "var(--bs-secondary-color)",
        img_src: "/blocks/images/google_logo.png",
        border_radius: "0.375rem",
      },
      formLoginLink: {
        id: "signup_form_login_link_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        text: "Log in",
        render: true,
        color: "rgba(var(--bs-link-color-rgb),var(--bs-link-opacity,1))",
      },
      formAlreadyHaveAnAccountTitle: {
        id: "signup_form_already_have_an_account_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        text: "Already have an account?",
        render: true,
        color: " var(--bs-secondary-color)!important",
      },
      formUntitledUITitle: {
        id: "signup_form_untitled_ui_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        text: "Untitled UI 2077",
        render: true,
        color: " var(--bs-secondary-color)!important",
      },
      formFooterEmailTitle: {
        id: "signup_form_footer_email_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        text: "help@untitledui.com",
        render: true,
        color: " var(--bs-secondary-color)!important",
      },
      formMainImageText: {
        id: "signup_form_main_image_text_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        text: "“We’ve been using Untitled to kick start every new project and can't imagine working withouit.”",
        render: true,
        color: "white !important",
      },
      formGoogleSignupLogo: {
        id: "signup_form_google_signup_logo_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        text: "/blocks/images/google_logo.png",
        render: true,
      },
      formLoginImageSRC: {
        id: "signup_form_login_image_src_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        text: "/blocks/images/logo.png",
        render: true,
      },
      formMainImageSRC: {
        id: "signup_form_main_image_src_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        text: "/blocks/images/MAIN_IMAGE_SRC.webp",
        render: true,
      },
      formLeftArrow: {
        id: "signup_form_left_arrow_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        color: "white",
        border_color: "white",
      },
      formRightArrow: {
        id: "signup_form_right_arrow_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        color: "white",
        border_color: "white",
      },
    },
  },
};
