import { BubblePosition } from "../types/Bubble";
import { BlockConfig } from "../types/Config";
import { PossiblePages } from "../types/Pages";

export const mayoralven_config: BlockConfig = {
  possiblePages: [PossiblePages.HOME, PossiblePages.FAQ],
  contents: {
    rightSection: {
      sectionInfo: {
        sectionTitle: "All",
      },
      mayoralvenMainContainer: {
        background_color: "white",
      },
      mayoralvenLogoImage: {
        id: "mayoralven_logo_image_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        img_src: "/blocks/images/mayoralven-logo.png",
      },
      mayoralvenLogoTitle: {
        id: "mayoralven_logo_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "mayoralven",
        color: "#000",
      },
      mayoralvenMainMenuStyle: {
        background_color: "rgba(var(--bs-white-rgb),var(--bs-bg-opacity))",
        box_shadow_color: "rgba(0, 0, 0, 0.1)",
      },

      mayoralvenMenu_0: {
        id: "mayoralven_menu_0_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Product",
        color: "var(--bs-nav-link-color)",
        class: "bi bi-house-door",
        icon_color: "var(--bs-nav-link-color)",
      },
      mayoralvenMenu_1: {
        id: "mayoralven_menu_1_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Features",
        color: "var(--bs-nav-link-color)",
        class: "bi bi-calendar",
        icon_color: "var(--bs-nav-link-color)",
      },
      mayoralvenMenu_2: {
        id: "mayoralven_menu_2_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Pricing",
        color: "var(--bs-nav-link-color)",
        class: "bi bi-graph-up",
        icon_color: "var(--bs-nav-link-color)",
      },
      mayoralvenMenu_3: {
        id: "mayoralven_menu_3_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Support",
        color: "var(--bs-nav-link-color)",
        class: "bi bi-gear",
        icon_color: "var(--bs-nav-link-color)",
      },

      mayoralvenLoginButton: {
        id: "mayoralven_login_button_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Login",
        color: "#6c757d",
        border_color: "#3361FF",
      },
      mayoralvenSignupButton: {
        id: "mayoralven_signup_button_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Sign up",
        color: "#33bf7e",
        border_color: "#33bf7e",
        border_radius: "0.375rem",
      },

      mayoralvenCard_0_Title_0: {
        id: "mayarolven_card_0_title_0",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Ecosystem",
        color: "gray",
      },
      mayoralvenCard_0_ItemIcon_0: {
        id: "mayarolven_card_0_item_icon_0",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-phone",
        color: "white",
        background_color: "#8dc2f6",
      },
      mayoralvenCard_0_Item_0: {
        id: "mayarolven_card_0_item_0",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Guest App",
        color: "#000000",
      },
      mayoralvenCard_0_ItemDesc_0: {
        id: "mayarolven_card_0_item_desc_0",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Lorem ipsum dolor sit amet, consect adipiscing elit",
        color: "var(--bs-secondary-color)!important",
      },
      mayoralvenCard_0_ItemCallAction_0: {
        id: "mayarolven_card_0_item_call_action_0",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Call to action",
        color: "#bc6b6b",
        class: "bi bi-arrow-right",
        icon_color: "#bc6b6b",
      },

      mayoralvenCard_0_ItemIcon_1: {
        id: "mayarolven_card_0_item_icon_1",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-phone",
        color: "white",
        background_color: "orange",
      },
      mayoralvenCard_0_Item_1: {
        id: "mayarolven_card_0_item_1",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "CMS",
        color: "#000000",
      },
      mayoralvenCard_0_ItemDesc_1: {
        id: "mayarolven_card_0_item_desc_1",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Lorem ipsum dolor sit amet, consect adipiscing elit",
        color: "var(--bs-secondary-color)!important",
      },
      mayoralvenCard_0_ItemCallAction_1: {
        id: "mayarolven_card_0_item_call_action_1",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Call to action",
        color: "orange",
        class: "bi bi-arrow-right",
        icon_color: "orange",
      },

      mayoralvenCard_0_ItemIcon_2: {
        id: "mayarolven_card_0_item_icon_2",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-people",
        color: "white",
        background_color: "purple",
      },
      mayoralvenCard_0_Item_2: {
        id: "mayarolven_card_0_item_2",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "CRM",
        color: "#000000",
      },
      mayoralvenCard_0_ItemDesc_2: {
        id: "mayarolven_card_0_item_desc_2",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Lorem ipsum dolor sit amet, consect adipiscing elit",
        color: "var(--bs-secondary-color)!important",
      },
      mayoralvenCard_0_ItemCallAction_2: {
        id: "mayarolven_card_0_item_call_action_2",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Call to action",
        color: "#a73da7",
        class: "bi bi-arrow-right",
        icon_color: "#a73da7",
      },

      mayoralvenCard_1_Title_0: {
        id: "mayarolven_card_1_title_0",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Ecosystem",
        color: "gray",
      },
      mayoralvenCard_1_ItemIcon_0: {
        id: "mayarolven_card_1_item_icon_0",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-journal-text",
        color: "#6c757d",
        background_color: "white",
      },
      mayoralvenCard_1_Item_0: {
        id: "mayarolven_card_1_item_0",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Directory",
        color: "#000000",
      },
      mayoralvenCard_1_ItemDesc_0: {
        id: "mayarolven_card_1_item_desc_0",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Lorem ipsum dolor sit amet, consect adipiscing elit",
        color: "var(--bs-secondary-color)!important",
      },

      mayoralvenCard_1_ItemIcon_1: {
        id: "mayarolven_card_1_item_icon_1",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-calendar",
        color: "#6c757d",
        background_color: "white",
      },
      mayoralvenCard_1_Item_1: {
        id: "mayarolven_card_1_item_1",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Bookings",
        color: "#000000",
      },
      mayoralvenCard_1_ItemDesc_1: {
        id: "mayarolven_card_1_item_desc_1",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Lorem ipsum dolor sit amet, consect adipiscing elit",
        color: "var(--bs-secondary-color)!important",
      },

      mayoralvenCard_1_ItemIcon_2: {
        id: "mayarolven_card_1_item_icon_2",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-chat-left-text",
        color: "#6c757d",
        background_color: "white",
      },
      mayoralvenCard_1_Item_2: {
        id: "mayarolven_card_1_item_2",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "User feedback",
        color: "#000000",
      },
      mayoralvenCard_1_ItemDesc_2: {
        id: "mayarolven_card_1_item_desc_2",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Lorem ipsum dolor sit amet, consect adipiscing elit",
        color: "var(--bs-secondary-color)!important",
      },

      mayoralvenCard_1_ItemIcon_3: {
        id: "mayarolven_card_1_item_icon_3",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-list-task",
        color: "#6c757d",
        background_color: "white",
      },
      mayoralvenCard_1_Item_3: {
        id: "mayarolven_card_1_item_3",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Task Manager",
        color: "#000000",
      },
      mayoralvenCard_1_ItemDesc_3: {
        id: "mayarolven_card_1_item_desc_3",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Lorem ipsum dolor sit amet, consect adipiscing elit",
        color: "var(--bs-secondary-color)!important",
      },

      mayoralvenCard_2_Title_0: {
        id: "mayarolven_card_2_title_0",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Ecosystem",
        color: "gray",
      },
      mayoralvenCard_2_ItemIcon_0: {
        id: "mayarolven_card_2_item_icon_0",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-diagram-3",
        color: "#6c757d",
        background_color: "white",
      },
      mayoralvenCard_2_Item_0: {
        id: "mayarolven_card_2_item_0",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Channel Manager",
        color: "#000000",
      },
      mayoralvenCard_2_ItemDesc_0: {
        id: "mayarolven_card_2_item_desc_0",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Lorem ipsum dolor sit amet, consect adipiscing elit",
        color: "var(--bs-secondary-color)!important",
      },

      mayoralvenCard_2_ItemIcon_1: {
        id: "mayarolven_card_2_item_icon_1",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-graph-up",
        color: "#6c757d",
        background_color: "white",
      },
      mayoralvenCard_2_Item_1: {
        id: "mayarolven_card_2_item_1",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Bookings",
        color: "#000000",
      },
      mayoralvenCard_2_ItemDesc_1: {
        id: "mayarolven_card_2_item_desc_1",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Lorem ipsum dolor sit amet, consect adipiscing elit",
        color: "var(--bs-secondary-color)!important",
      },

      mayoralvenCard_2_ItemIcon_2: {
        id: "mayarolven_card_2_item_icon_2",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        class: "bi bi-gear",
        color: "#6c757d",
        background_color: "white",
      },
      mayoralvenCard_2_Item_2: {
        id: "mayarolven_card_2_item_2",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Settings",
        color: "#000000",
      },
      mayoralvenCard_2_ItemDesc_2: {
        id: "mayarolven_card_2_item_desc_2",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Lorem ipsum dolor sit amet, consect adipiscing elit",
        color: "var(--bs-secondary-color)!important",
      },

      mayoralvenSidebarContainer: {
        background_color: "#f9f9f9",
      },

      mayoralvenSidebar_0_Image: {
        id: "mayarolven_sidebar_0_image_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        img_src: "/blocks/images/mayoralven-sidebar-1.png",
      },
      mayoralvenSidebar_0_Title: {
        id: "mayarolven_sidebar_0_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Check the new app",
        color: "var(--bs-card-title-color)",
      },
      mayoralvenSidebar_0_TitleBadge: {
        id: "mayarolven_sidebar_0_title_badge_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Featured",
        color: "gray",
        border_color: "gray",
      },
      mayoralvenSidebar_0_Desc: {
        id: "mayarolven_sidebar_0_desc_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Lorem ipsum dolor sit amet, consect adipiscing elit",
        color: "#6c757d",
      },
      mayoralvenSidebar_0_CallAction: {
        id: "mayarolven_sidebar_0_call_action",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Call to action",
        color: "#bc6b6b",
        class: "bi bi-arrow-right",
        icon_color: "#bc6b6b",
      },

      mayoralvenSidebar_1_Image: {
        id: "mayarolven_sidebar_1_image_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        img_src: "/blocks/images/mayoralven-sidebar-2.png",
      },
      mayoralvenSidebar_1_Title: {
        id: "mayarolven_sidebar_1_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Check our newsletter",
        color: "var(--bs-card-title-color)",
      },
      mayoralvenSidebar_1_Desc: {
        id: "mayarolven_sidebar_1_desc_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Lorem ipsum dolor sit amet, consect adipiscing elit",
        color: "#6c757d",
      },
      mayoralvenSidebar_1_CallAction: {
        id: "mayarolven_sidebar_1_call_action",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Call to action",
        color: "#bc6b6b",
        class: "bi bi-arrow-right",
        icon_color: "#bc6b6b",
      },
    },
  },
};
