import { BubblePosition } from "../types/Bubble";
import { BlockConfig } from "../types/Config";
import { PossiblePages } from "../types/Pages";

export const getintouch_config: BlockConfig = {
  possiblePages: [PossiblePages.HOME, PossiblePages.FAQ],
  contents: {
    rightSection: {
      sectionInfo: {
        sectionTitle: "All",
      },
      getintouchMainContainer: {
        background_color: "white",
      },
      getintouchLogoImage: {
        id: "getintouch_logo_image_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        img_src: "/blocks/images/logo.png",
      },
      getintouchLogoTitle: {
        id: "getintouch_logo_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Untitled UI",
        color: "#000",
      },
      getintouchMainMenuStyle: {
        background_color: "rgba(var(--bs-white-rgb),var(--bs-bg-opacity))",
      },

      getintouchMenu_0: {
        id: "getintouch_menu_0_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Home",
        color: "gray",
      },
      getintouchMenu_1: {
        id: "getintouch_menu_1_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Products",
        color: "gray",
        class: "bi bi-chevron-down",
        icon_color: "gray",
      },
      getintouchMenu_2: {
        id: "getintouch_menu_2_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Resources",
        color: "gray",
        class: "bi bi-chevron-down",
        icon_color: "gray",
      },
      getintouchMenu_3: {
        id: "getintouch_menu_3_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Pricing",
        color: "gray",
      },

      getintouchLoginButton: {
        id: "getintouch_login_button_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Login",
        color: "#gray",
      },
      getintouchSignupButton: {
        id: "getintouch_signup_button_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Sign up",
        color: "#b434b",
        border_color: "#b434b",
        border_radius: "0.375rem",
      },

      getintouchFormTitle: {
        id: "getintouch_form_title_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Get in touch",
        color: "black",
      },
      getintouchFormDesc: {
        id: "getintouch_form_desc_id",
        bubble: true,
        bubblePosition: BubblePosition.LEFT,
        render: true,
        text: "Our friendly team would love to hear from you.",
        color: "gray",
      },

      getintouchFormFirstNameLabel: {
        id: "getintouch_form_firstname_label_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "First name",
        color: "#000000",
      },
      getintouchFormFirstNameInput: {
        id: "getintouch_form_firstname_input_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        placeholder_text: "First name",
        placeholder_color: "gray",
        border_color: "rgb(222,226,230)",
      },
      getintouchFormLastNameLabel: {
        id: "getintouch_form_lastname_label_id",
        bubble: true,
        bubblePosition: BubblePosition.RIGHT,
        render: true,
        text: "Last name",
        color: "#000000",
      },
      getintouchFormLastNameInput: {
        id: "getintouch_form_lastname_input_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        placeholder_text: "Last name",
        placeholder_color: "gray",
        border_color: "rgb(222,226,230)",
      },
      getintouchFormEmailLabel: {
        id: "getintouch_form_email_label_id",
        bubble: true,
        bubblePosition: BubblePosition.LEFT,
        render: true,
        text: "Email",
        color: "#000000",
      },
      getintouchFormEmailInput: {
        id: "getintouch_form_email_input_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        placeholder_text: "you@company.com",
        placeholder_color: "gray",
        border_color: "rgb(222,226,230)",
      },
      getintouchFormPhoneNumberLabel: {
        id: "getintouch_form_phonenumber_label_id",
        bubble: true,
        bubblePosition: BubblePosition.LEFT,
        render: true,
        text: "Phone Number",
        color: "#000000",
      },
      getintouchFormPhoneNumberSelect: {
        id: "getintouch_form_phonenumber_select_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        placeholder_text: "+1(555) 000-0000",
        placeholder_color: "gray",
        color: "black",
        border_color: "rgb(222,226,230)",
      },
      getintouchFormPhoneNumberSelectOption_0: {
        id: "getintouch_form_phonenumber_input_option_0_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "US",
        color: "red",
      },
      getintouchFormPhoneNumberSelectOption_1: {
        id: "getintouch_form_phonenumber_input_option_1_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "UK +44",
        color: "black",
      },
      getintouchFormMessageLabel: {
        id: "getintouch_form_message_label_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Message",
        color: "#000000",
      },
      getintouchFormMessageInput: {
        id: "getintouch_form_message_input_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        placeholder_text: "you@company.com",
        placeholder_color: "gray",
        border_color: "rgb(222,226,230)",
      },
      getintouchFormPrivacyPolicyInput: {
        id: "getintouch_form_privacypolicy_input_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        placeholder_text: "you@company.com",
        placeholder_color: "gray",
      },
      getintouchFormPrivacyPolicyLabel: {
        id: "getintouch_form_privacypolicy_label_id",
        bubble: true,
        bubblePosition: BubblePosition.LEFT,
        render: true,
        text: "You agree to our friendly",
        color: "gray",
      },
      getintouchFormPrivacyPolicyLink: {
        id: "getintouch_form_privacypolicy_link_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "privacy policy",
        color: "gray",
      },

      getintouchSendMessageButton: {
        id: "getintouch_send_message_button_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        text: "Send Message",
        color: "#b434b",
        border_color: "#b434b",
        border_radius: "0.375rem",
      },

      getintouchMainImage: {
        id: "getintouch_main_image_id",
        bubble: true,
        bubblePosition: BubblePosition.TOP,
        render: true,
        img_src: "/blocks/images/getintouch_right_image.png",
      },
    },
  },
};
